name: "Setup Common Fate CLI"
description: "GitHub Action to install and configure the Common Fate CLI"
branding:
  icon: arrow-down-circle
  color: gray-dark
inputs:
  version:
    description: "The CLI version to install"
    required: true
    default: "1.11.0"
  oidc-client-id:
    description: "The OIDC client ID to authenticate with"
    required: true
  oidc-client-secret:
    description: "The OIDC client secret to authenticate with"
    required: true
  oidc-issuer:
    description: "The OIDC issuer to authenticate with"
    required: true
  api-url:
    description: "The Common Fate API URL"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Download 'cf' CLI
      shell: bash
      env:
        CLI_VERSION: ${{ inputs.version }}
      run: |
        # import the Common Fate signing key
        gpg --import common-fate-signing-key.asc

        curl -OL releases.commonfate.io/cf/v${CLI_VERSION}/cf_${CLI_VERSION}_linux_x86_64.tar.gz

        # verify the CLI signature (see: https://docs.commonfate.io/granted/security)
        curl -OL releases.commonfate.io/cf/v${CLI_VERSION}/checksums.txt
        curl -OL releases.commonfate.io/cf/v${CLI_VERSION}/checksums.txt.sig
        shasum -a 256 -c checksums.txt --ignore-missing
        gpg --verify ./checksums.txt.sig

        sudo tar -zxvf ./cf_${CLI_VERSION}_linux_x86_64.tar.gz -C /usr/local/bin/

    - name: Export environment variables to configure the CLI
      shell: bash
      run: |
        echo "CF_OIDC_CLIENT_ID=${{ inputs.oidc-client-id }}" >> $GITHUB_ENV
        echo "CF_OIDC_CLIENT_SECRET=${{ inputs.oidc-client-secret }}" >> $GITHUB_ENV
        echo "CF_OIDC_ISSUER=${{ inputs.oidc-issuer }}" >> $GITHUB_ENV
        echo "CF_API_URL=${{ inputs.api-url }}" >> $GITHUB_ENV
